
#ifndef _MDRV_DEMOD_IO_H_
#define _MDRV_DEMOD_IO_H_

/* Use 'F' as magic number */
#define DEMOD_IOC_MAGIC             'F'

#define DEMOD_IOC_INIT              _IO(DEMOD_IOC_MAGIC, 0)
#define DEMOD_IOC_RESET             _IO(DEMOD_IOC_MAGIC, 1)
#define DEMOD_IOC_REG_WRITE         _IOW(DEMOD_IOC_MAGIC, 2, DEMOD_REG_t)
#define DEMOD_IOC_REG_READ          _IOWR(DEMOD_IOC_MAGIC, 3, DEMOD_REG_t)
#define DEMOD_IOC_MB_REG_WRITE      _IOW(DEMOD_IOC_MAGIC, 4, DEMOD_REG_t)
#define DEMOD_IOC_MB_REG_READ       _IOWR(DEMOD_IOC_MAGIC, 5, DEMOD_REG_t)
//Driver update 2009/11/20
#define DEMOD_IOC_MB_DSPREG_WRITE   _IOW(DEMOD_IOC_MAGIC, 6, DEMOD_REG_t)
#define DEMOD_IOC_MB_DSPREG_READ    _IOWR(DEMOD_IOC_MAGIC, 7, DEMOD_REG_t)
#define DEMOD_IOC_MB_REG_WRITE_ATSC _IOW(DEMOD_IOC_MAGIC, 8, DEMOD_REG_t)
#define DEMOD_IOC_MB_REG_READ_ATSC  _IOWR(DEMOD_IOC_MAGIC, 9, DEMOD_REG_t)
#define DEMOD_IOC_LOAD_DSP_CODE     _IOW(DEMOD_IOC_MAGIC, 10, DEMOD_STANDARD_TYPE_t)
#define DEMOD_IOC_STOP              _IOW(DEMOD_IOC_MAGIC, 11, DEMOD_STANDARD_TYPE_t)//mstar 0901 update

#define DEMOD_IOC_MB_REG_WRITE_ISDBT _IOW(DEMOD_IOC_MAGIC, 12, DEMOD_REG_t)
#define DEMOD_IOC_MB_REG_READ_ISDBT  _IOWR(DEMOD_IOC_MAGIC, 13, DEMOD_REG_t)
#define DEMOD_IOC_MB_REG_WRITE_DTMB _IOW(DEMOD_IOC_MAGIC, 14, DEMOD_REG_t)
#define DEMOD_IOC_MB_REG_READ_DTMB  _IOWR(DEMOD_IOC_MAGIC, 15, DEMOD_REG_t)

#define DEMOD_IOC_DVBEXT_SET_STATE  _IOW(DEMOD_IOC_MAGIC, 16, DEMOD_DVBEXT_STATE_t)
#define DEMOD_IOC_DVBEXT_GET_STATE  _IOR(DEMOD_IOC_MAGIC, 17, DEMOD_DVBEXT_STATE_t)

#define DEMOD_IOC_MAXNR             18
#endif
