#-----------------------------------------------------------------------------------------
# H13 arch default devices
#-----------------------------------------------------------------------------------------
INCLUDE_KDRV_SAMPLE	:= NO
INCLUDE_KDRV_AAD	:= YES
INCLUDE_KDRV_AUDIO	:= YES
INCLUDE_KDRV_AFE	:= YES
INCLUDE_KDRV_CI		:= YES
INCLUDE_KDRV_DE		:= YES
INCLUDE_KDRV_DEMOD	:= YES
INCLUDE_KDRV_DENC	:= YES
INCLUDE_KDRV_FBDEV	:= YES
INCLUDE_KDRV_GFX	:= YES
INCLUDE_KDRV_GPU	:= YES
INCLUDE_KDRV_GPIO	:= YES
INCLUDE_KDRV_HDMI	:= YES
INCLUDE_KDRV_I2C	:= YES
INCLUDE_KDRV_PE		:= YES
INCLUDE_KDRV_PVR	:= YES
INCLUDE_KDRV_SDEC	:= YES
INCLUDE_KDRV_VBI	:= YES
INCLUDE_KDRV_VDEC	:= YES
INCLUDE_KDRV_VENC	:= YES
INCLUDE_KDRV_PNG	:= YES
INCLUDE_KDRV_SE		:= YES
INCLUDE_KDRV_SYS	:= YES
INCLUDE_KDRV_SCI	:= YES
INCLUDE_KDRV_CLK	:= YES
INCLUDE_KDRV_MONITOR:= YES
INCLUDE_KDRV_MJPEG	:= YES
INCLUDE_KDRV_APR	:= YES
INCLUDE_KDRV_MEMPROT:= YES

INCLUDE_KDRV_BE		:= YES
INCLUDE_KDRV_LGBUS	:= YES
INCLUDE_KDRV_OVI	:= YES
INCLUDE_KDRV_LOGM 	:= YES

#-----------------------------------------------------------------------------------------
# H13 arch default PM
#-----------------------------------------------------------------------------------------
KDRV_CONFIG_PM_SAMPLE	:= NO
KDRV_CONFIG_PM_AAD		:= YES
KDRV_CONFIG_PM_AUDIO	:= YES
KDRV_CONFIG_PM_AFE		:= YES
KDRV_CONFIG_PM_CI		:= YES
KDRV_CONFIG_PM_DE		:= YES
KDRV_CONFIG_PM_DEMOD	:= YES
KDRV_CONFIG_PM_DENC		:= YES
KDRV_CONFIG_PM_FBDEV	:= YES
KDRV_CONFIG_PM_GFX		:= YES
KDRV_CONFIG_PM_GPU		:= YES
KDRV_CONFIG_PM_GPIO		:= YES
KDRV_CONFIG_PM_HDMI		:= YES
KDRV_CONFIG_PM_I2C		:= YES
KDRV_CONFIG_PM_PE		:= YES
KDRV_CONFIG_PM_PVR		:= YES
KDRV_CONFIG_PM_SDEC		:= YES
KDRV_CONFIG_PM_VBI		:= YES
KDRV_CONFIG_PM_VDEC		:= YES
KDRV_CONFIG_PM_VENC		:= YES
KDRV_CONFIG_PM_PNG		:= YES
KDRV_CONFIG_PM_SE		:= YES
KDRV_CONFIG_PM_SYS		:= YES
KDRV_CONFIG_PM_SCI		:= YES
KDRV_CONFIG_PM_CLK		:= YES
KDRV_CONFIG_PM_MONITOR	:= YES
KDRV_CONFIG_PM_MJPEG	:= YES
KDRV_CONFIG_PM_APR		:= YES
KDRV_CONFIG_PM_MEMPROT	:= YES

KDRV_CONFIG_PM_BE		:= YES
KDRV_CONFIG_PM_LGBUS	:= YES
KDRV_CONFIG_PM_OVI		:= YES
KDRV_CONFIG_PM_LOGM 	:= YES

