obj-$(CONFIG_MMCOOPS)		+=mmcoops.o
obj-$(CONFIG_WDT_LOG)		+=wdt_log.o
obj-$(CONFIG_WDT_DETECT_LG1K)	+=wdt_detect_lg1k.o
obj-$(CONFIG_WDT_DETECT_MSTAR)	+=wdt_detect_mstar.o
obj-$(CONFIG_LL_MMC)		+=ll_mmc.o
obj-$(CONFIG_LL_MMC_LG1K)	+=ll_mmc_lg1k.o
obj-$(CONFIG_LL_MMC_MSTAR)	+=ll_mmc_mstar.o
