#-----------------------------------------------------------------------------------------
# arch_dev.mk describles the default device description
#-----------------------------------------------------------------------------------------
include $(KDRV_TOP_DIR)/../chip/h14/os/arch_dev.mk

INCLUDE_KDRV_SAMPLE	= NO #NO
INCLUDE_KDRV_AAD	= NO #YES
INCLUDE_KDRV_AUDIO	= NO #YES
INCLUDE_KDRV_AFE	= NO #YES
INCLUDE_KDRV_CI		= NO #YES
INCLUDE_KDRV_DE		= YES
INCLUDE_KDRV_DEMOD	= NO #YES
INCLUDE_KDRV_DENC	= NO #YES
INCLUDE_KDRV_DIMM	= NO #YES
INCLUDE_KDRV_FBDEV	= YES
INCLUDE_KDRV_FMT3D	= NO #NO
INCLUDE_KDRV_FRC	= YES
INCLUDE_KDRV_GFX	= YES
INCLUDE_KDRV_GPU	= NO #YES
INCLUDE_KDRV_GPIO	= YES
INCLUDE_KDRV_HDMI	= NO #YES
INCLUDE_KDRV_I2C	= YES
INCLUDE_KDRV_PE		= NO 
INCLUDE_KDRV_PVR	= YES
INCLUDE_KDRV_SDEC	= YES
INCLUDE_KDRV_VBI	= NO #YES
INCLUDE_KDRV_VDEC	= YES
INCLUDE_KDRV_VENC	= YES
INCLUDE_KDRV_PNG	= NO
INCLUDE_KDRV_SE		= NO #YES
INCLUDE_KDRV_SYS	= YES
INCLUDE_KDRV_SCI	= NO #YES
INCLUDE_KDRV_CLK	= NO #YES
INCLUDE_KDRV_MONITOR    = NO #YES
INCLUDE_KDRV_MJPEG	= NO
INCLUDE_KDRV_APR	= NO #YES
INCLUDE_KDRV_LGBUS	= NO
INCLUDE_KDRV_MEMPROT = NO #YES 
