#
# Makefile for MStar device drivers.
#
obj-$(CONFIG_MSTAR_CMAPOOL)                 += drv/cma_pool/
obj-$(CONFIG_MSTAR_EMAC)                    += drv/emac/
obj-$(CONFIG_MSTAR_GPIO)                    += drv/gpio/
obj-$(CONFIG_MSTAR_IIC)                     += drv/iic/
obj-$(CONFIG_MSTAR_IOMAP)                   += drv/iomap/
obj-$(CONFIG_MSTAR_IR)                      += drv/ir/
obj-$(CONFIG_MSTAR_MIU)                     += drv/miu/
obj-$(CONFIG_MSTAR_MPOOL)                   += drv/mpool/
obj-$(CONFIG_MSTAR_NAND)                    += drv/nand/
obj-$(CONFIG_MSTAR_SYSTEM)                  += drv/system/
obj-$(CONFIG_SYSTEM_LG)                     += drv/system_LG/
obj-$(CONFIG_MSTAR_MMC)                     += drv/mmc/
obj-$(CONFIG_MSTAR_MBX)                     += drv/mbx/
obj-$(CONFIG_MSTAR_FUSION)                  += drv/fusion/
obj-$(CONFIG_MSTAR_SAR)                     += drv/sar/
obj-$(CONFIG_MSTAR_SC)                      += drv/sc/
obj-$(CONFIG_MSTAR_ALSA_AUDIO_DRIVER_DRV)   += drv/alsa_audio_driver/
obj-$(CONFIG_MSTAR_SEMUTEX)                 += drv/semutex/
obj-$(CONFIG_MSTAR_DEMOD)                   += drv/demod/
obj-$(CONFIG_MSTAR_VIF)                     += drv/vif/
obj-$(CONFIG_MSTAR_DLMALLOC)                += drv/dlmalloc/
obj-$(CONFIG_MSTAR_FB)                      += drv/mstar_fb/
