#include <linux/kernel.h>
#include <linux/string.h>
#include <linux/slab.h>
#include <asm/uaccess.h>

#include "VDEC_EX_adp.h"
#include "utopia.h"
#include "utopia_adp.h"
//#include "drvVDEC.h"
#include "apiVDEC_MultiDec.h"
#include "apiVDEC_EX_v2.h"

#include "MsDevice.h"


#ifdef MSOS_TYPE_LINUX_KERNEL

#ifndef CPY_FROM_USER
#define CPY_FROM_USER                   copy_from_user
#endif
#ifndef CPY_to_USER
#define CPY_to_USER                     copy_to_user
#endif

#else
#ifndef CPY_FROM_USER
#define CPY_FROM_USER                   memcpy
#endif
#ifndef CPY_to_USER
#define CPY_to_USER                     memcpy
#endif

#endif


typedef struct
{
    VDEC_EX_IapGnBufShareBWMode* pVDEC_EX_IapGnBufShareBWMode;
} VDEC_EX_PtrIapGnBufShareBWMode;

typedef struct
{
    VDEC_EX_DecModCfg* pVDEC_EX_DecModCfg;
} VDEC_EX_PtrDecModCfg;



//E_VDEC_EX_V2_CMD_GET_FREE_STREAM_ID
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_STREAM_V2_ID,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_STREAM_ID,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_STREAM_TYPE,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_CODEC_TYPE,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_FREE_STREAM_ID,6);
//E_VDEC_EX_V2_CMD_INIT
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_INIT_PARAM,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_INIT,3);
//E_VDEC_EX_V2_CMD_SET_CONTROL
//E_VDEC_EX_V2_USER_CMD_CHECK_DISPINFO_READY:
//E_VDEC_EX_V2_USER_CMD_PLAY:
//E_VDEC_EX_V2_USER_CMD_PAUSE:
//E_VDEC_EX_V2_USER_CMD_RESUME:
//E_VDEC_EX_V2_USER_CMD_STEP_DISP:
//E_VDEC_EX_V2_USER_CMD_STEP_DECODE:
//E_VDEC_EX_V2_USER_CMD_FIRE_DEC:
//E_VDEC_EX_V2_USER_CMD_MHEG_RST_IFRAME_DEC:
//E_VDEC_EX_V2_USER_CMD_CC_STOP_PARSING:
//E_VDEC_EX_V2_USER_CMD_RST:
//E_VDEC_EX_V2_USER_CMD_EXIT:
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_IO,2);
//E_VDEC_EX_V2_USER_CMD_SET_FRC_MODE
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_FRC_MODE,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_SET_FRC_MODE,3);
//E_VDEC_EX_V2_USER_CMD_SET_DYNSCALING_PARAMS
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_ADDR,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_SET_DYNSCALING_PARAMS,4);
//E_VDEC_EX_V2_USER_CMD_SET_DBG_LEVEL
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_DBG_LEVEL,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_SET_DBG_LEVEL,3);
//E_VDEC_EX_V2_USER_CMD_SET_TRICK_MODE
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_TRICK_DEC,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_SET_TRICK_MODE,3);
//E_VDEC_EX_V2_USER_CMD_PUSH_DECQ
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_DEC_CMD,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_PUSH_DECQ,3);
//E_VDEC_EX_V2_USER_CMD_FLUSH
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_FREEZE_PIC_SELECT,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_FLUSH,3);
//E_VDEC_EX_V2_USER_CMD_ENABLE_LAST_FRAME_SHOW:
//E_VDEC_EX_V2_USER_CMD_SET_FREEZE_DISP:
//E_VDEC_EX_V2_USER_CMD_SET_BLUE_SCREEN:
//E_VDEC_EX_V2_USER_CMD_DISABLE_DEBLOCKING:
//E_VDEC_EX_V2_USER_CMD_DISABLE_QUARTER_PIXEL:
//E_VDEC_EX_V2_USER_CMD_SET_AUTO_RM_LST_ZERO_BYTE:
//E_VDEC_EX_V2_USER_CMD_SET_BLOCK_DISPLAY:
//E_VDEC_EX_V2_USER_CMD_ENABLE_ES_BUFF_MALLOC:
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_BOOL,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_IO_BOOL,3);
//E_VDEC_EX_V2_USER_CMD_SET_SPEED
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_SPEED_TYPE,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_SPEED,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_SET_SPEED,4);
//E_VDEC_EX_V2_USER_CMD_RESET_PTS:
//E_VDEC_EX_V2_USER_CMD_AVSYNC_FREERUN_THRESHOLD:
//E_VDEC_EX_V2_USER_CMD_SEEK_TO_PTS:
//E_VDEC_EX_V2_USER_CMD_SKIP_TO_PTS:// TODO: what's the difference between skip & seek?
//E_VDEC_EX_V2_USER_CMD_CC_INIT;
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_U32,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_IO_U32,3);
//E_VDEC_EX_V2_USER_CMD_AVSYNC_ON
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_SYNC_TOLERANCE,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_AVSYNC_ON,5);
//E_VDEC_EX_V2_USER_CMD_UNSET_EVENT_MULTICALLBACK
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_TYPE,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_UNSET_EVENT_MULTICALLBACK,4);
//E_VDEC_EX_V2_USER_CMD_SET_BALANCE_BW
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_SET_BALANCE_BW,6);
//E_VDEC_EX_V2_USER_CMD_GEN_PATTERN
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_PATTERN_TYPE,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GEN_PATTERN,5);
//E_VDEC_EX_V2_USER_CMD_MHEG_DECODE_IFRAME:
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_MHEG_DECODE_IFRAME,5);
//E_VDEC_EX_V2_USER_CMD_CC_START_PARSING:
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_CC_CONFIG,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_CC_START_PARSING,3);
//E_VDEC_EX_V2_USER_CMD_DISPLAY_FRAME:
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_DISP_FRAME,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_DISP_RELEASE_FRAME,3);
//E_VDEC_EX_V2_USER_CMD_CAPTURE_FRAME
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_CAPTURE_FRAME,4);
//E_VDEC_EX_V2_USER_CMD_CC_SET_CFG:
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_CC_FORMAT,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_CC_TYPE,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_CC_INPUT_PARAM,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_CC_SET_CFG,5);
//E_VDEC_EX_V2_USER_CMD_CC_SET_BUFF_START_ADDR
//E_VDEC_EX_V2_USER_CMD_CC_UPDATE_WRITE_ADDR:
//E_VDEC_EX_V2_USER_CMD_CC_UPDATE_READ_ADDR:
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_CC_UPDATE_ADDR,4);
//E_VDEC_EX_V2_USER_CMD_CC_DISABLE_PARSING:
//E_VDEC_EX_V2_USER_CMD_CC_GET_IS_RST_DONE
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_CC_IO_CC_FORMAT,3);
//E_VDEC_EX_V2_USER_CMD_GETLIBVER:
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_MSIF_VERSION,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_LIBVER,3);
//E_VDEC_EX_V2_USER_CMD_GETINFO:
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_INFO,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_INFO,3);
//E_VDEC_EX_V2_USER_CMD_CHECKCAPS
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_CHECK_CAPS,4);
//E_VDEC_EX_V2_USER_CMD_GET_DISP_INFO:
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_DISP_INFO,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_DISP_INFO,3);
//E_VDEC_EX_V2_USER_CMD_GET_EXT_DISP_INFO
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_EXT_DISP_INFO,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_EXT_DISP_INFO,3);
//E_VDEC_EX_V2_USER_CMD_GET_DEC_FRAME_INFO
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_FRAME_INFO,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_DEC_FRAME_INFO,3);
//E_VDEC_EX_V2_USER_CMD_GET_DEC_TIMECODE
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_TIME_CODE,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_DEC_TIMECODE,3);

//E_VDEC_EX_V2_USER_CMD_GET_COLOUR_PRIMARIES
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_U8,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_IO_U8,3);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_COLOUR_PRIMARIES,3);
//E_VDEC_EX_V2_USER_CMD_GET_FW_VERSION
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_FW_TYPE,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_FW_VERSION,4);
//E_VDEC_EX_V2_USER_CMD_GET_VIDEO_PTS_STC_DELTA
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_U64,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_SET_GET_U64,3);
//E_VDEC_EX_V2_USER_CMD_GET_ERR_CODE
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_ERR_CODE,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_ERR_CODE,3);
//E_VDEC_EX_V2_USER_CMD_GET_CC_INFO
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_CC_INFO,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_CC_INFO,4);
//E_VDEC_EX_V2_USER_CMD_GET_ACTIVE_CODEC_TYPE
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_ACTIVE_CODEC_TYPE,3);
//E_VDEC_EX_V2_USER_CMD_GET_PATTERN_LEAST_LENGTH
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_PATTERN_LEAST_LENGTH,4);
//E_VDEC_EX_V2_USER_CMD_GET_ES_BUFF
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_ES_BUFF,5);
//E_VDEC_EX_V2_USER_CMD_CC_GET_INFO
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_CC_INFO_CMD,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_CC_GET_INFO,5);
//E_VDEC_EX_V2_USER_CMD_CC_GET_WRITE_ADDR
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_CC_GET_RW_ADDR,4);
//E_VDEC_EX_V2_USER_CMD_FRC_OUTPUT
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_FRC_OUTPUT_PARAM,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_FRC_OUTPUT,3);
//E_VDEC_EX_V2_USER_CMD_UT_SET_DBG_MODE
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_DBG_MODE,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_UT_SET_DBG_MODE,3);
//E_VDEC_EX_V2_USER_CMD_FIELD_POLARITY_DISPLAY_ONE_FIELD
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_FIELD_POLARITY,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_FIELD_POLARITY_DISPLAY_ONE_FIELD,3);
//E_VDEC_EX_V2_USER_CMD_SET_EXTERNAL_DS_BUFFER
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_EXTERNAL_DS_BUF,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_SET_EXTERNAL_DS_BUFFER,3);
//E_VDEC_EX_V2_USER_CMD_ENABLE_DECODE_ENGINE_TIMEOUT
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_TIMEOUT_PARAM,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_ENABLE_DECODE_ENGINE_TIMEOUT,3);
//E_VDEC_EX_V2_USER_CMD_SET_ERROR_TOLERANCE
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_ERR_TOLERANCE,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_SET_ERROR_TOLERANCE,3);
//E_VDEC_EX_V2_USER_CMD_GET_MAIN_STREAM_ID
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_STREAM_ID,3);
//E_VDEC_EX_V2_USER_CMD_GET_FPA_SEI
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_FRAME_PACKING_SIE,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_FPA_SEI,3);
//E_VDEC_EX_V2_USER_CMD_GET_FPA_SEI_EX
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_VER_CTRL,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_FPA_SEI_EX,3);
//E_VDEC_EX_V2_USER_CMD_GET_CRC_VALUE
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_CRC_VALUE,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_CRC_VALUE,3);
//E_VDEC_EX_V2_USER_CMD_GET_FRAME_INFO_EX:
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_FRAME_INFO_EX,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_FRAME_INFO_EX,3);
//E_VDEC_EX_V2_USER_CMD_PREGETSTATUS
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_STATUS,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_PREGETSTATUS,3);
//E_VDEC_EX_V2_USER_CMD_SYSTEM_PRESET_VPU_CLOCK
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_CLOCK_SPEED,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_SYSTEM_PRESET_CLOCK,3);
//E_VDEC_EX_V2_USER_CMD_SETPOWERSTATE
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_POWER_MODE,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_SET_POWERSTATE,3);

//E_VDEC_EX_V2_USER_CMD_PRESET_DECODE_MODE
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_DEC_MOD_CFG,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_PTR_DEC_MOD_CFG,1);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_PRESET_DECODE_MODE,3);

//E_VDEC_EX_V2_USER_CMD_HVD_IAPGN_BUF_SHARE_BW_MODE
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_IAP_GnBufShareBWMode,0);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_PTR_IAP_GnBufShareBWMode,1);
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_HVD_IAPGN_BUF_SHARE_BW_MODE,3);

//E_VDEC_EX_V2_USER_CMD_GET_EVENT_FLAG
UADP_SPT_NAMEnNXT_DEF(VDEC_EX_GET_EVENT_FLAG,4);














MS_U32 VDEC_EX_adp_Init(FUtopiaIOctl* pIoctl)
{
    UADP_SPT_NAME0NXT(VDEC_EX_STREAM_V2_ID,VDEC_EX_V2_StreamId);
    UADP_SPT_NAME0NXT(VDEC_EX_STREAM_ID,VDEC_StreamId);
    UADP_SPT_NAME0NXT(VDEC_EX_STREAM_TYPE,VDEC_EX_Stream);
    UADP_SPT_NAME0NXT(VDEC_EX_CODEC_TYPE,VDEC_EX_CodecType);
    UADP_SPT_NAME0NXT(VDEC_EX_INIT_PARAM,VDEC_EX_InitParam);
    UADP_SPT_NAME0NXT(VDEC_EX_FRC_MODE,VDEC_EX_FrcMode);
    UADP_SPT_NAME0NXT(VDEC_EX_ADDR,MS_PHYADDR);
    UADP_SPT_NAME0NXT(VDEC_EX_DBG_LEVEL,VDEC_EX_DbgLevel);
    UADP_SPT_NAME0NXT(VDEC_EX_TRICK_DEC,VDEC_EX_TrickDec);
    UADP_SPT_NAME0NXT(VDEC_EX_DEC_CMD,VDEC_EX_DecCmd);
    UADP_SPT_NAME0NXT(VDEC_EX_FREEZE_PIC_SELECT,VDEC_EX_FreezePicSelect);
    UADP_SPT_NAME0NXT(VDEC_EX_BOOL,MS_BOOL);
    UADP_SPT_NAME0NXT(VDEC_EX_SPEED_TYPE,VDEC_EX_SpeedType);
    UADP_SPT_NAME0NXT(VDEC_EX_SPEED,VDEC_EX_DispSpeed);
    UADP_SPT_NAME0NXT(VDEC_EX_U32,MS_U32);
    UADP_SPT_NAME0NXT(VDEC_EX_SYNC_TOLERANCE,MS_U16);
    UADP_SPT_NAME0NXT(VDEC_EX_TYPE,VDEC_EX_CB_TYPE);
    UADP_SPT_NAME0NXT(VDEC_EX_PATTERN_TYPE,VDEC_EX_PatternType);
    UADP_SPT_NAME0NXT(VDEC_EX_CC_CONFIG,VDEC_EX_CCCfg);
    UADP_SPT_NAME0NXT(VDEC_EX_DISP_FRAME,VDEC_EX_DispFrame);
    UADP_SPT_NAME0NXT(VDEC_EX_CC_FORMAT,VDEC_EX_CCFormat);
    UADP_SPT_NAME0NXT(VDEC_EX_CC_TYPE,VDEC_EX_CCType);
    UADP_SPT_NAME0NXT(VDEC_EX_CC_INPUT_PARAM,VDEC_EX_CC_InputPara);
    UADP_SPT_NAME0NXT(VDEC_EX_MSIF_VERSION,MSIF_Version);
    UADP_SPT_NAME0NXT(VDEC_EX_INFO,VDEC_EX_Info);
    UADP_SPT_NAME0NXT(VDEC_EX_DISP_INFO,VDEC_EX_DispInfo);
    UADP_SPT_NAME0NXT(VDEC_EX_EXT_DISP_INFO,VDEC_EX_ExtDispInfo);
    UADP_SPT_NAME0NXT(VDEC_EX_FRAME_INFO,VDEC_EX_FrameInfo);
    UADP_SPT_NAME0NXT(VDEC_EX_TIME_CODE,VDEC_EX_TimeCode);
    UADP_SPT_NAME0NXT(VDEC_EX_U8,MS_U8);
    UADP_SPT_NAME0NXT(VDEC_EX_FW_TYPE,VDEC_EX_FwType);
    UADP_SPT_NAME0NXT(VDEC_EX_U64,MS_U64);
    UADP_SPT_NAME0NXT(VDEC_EX_ERR_CODE,VDEC_EX_ErrCode);
    UADP_SPT_NAME0NXT(VDEC_EX_CC_INFO,VDEC_EX_CC_Info);
    UADP_SPT_NAME0NXT(VDEC_EX_CC_INFO_CMD,VDEC_EX_CCInfoCmd);
    UADP_SPT_NAME0NXT(VDEC_EX_FRC_OUTPUT_PARAM,VDEC_EX_FRC_OutputParam);
    UADP_SPT_NAME0NXT(VDEC_EX_DBG_MODE,VDEC_EX_DbgMode);
    UADP_SPT_NAME0NXT(VDEC_EX_FIELD_POLARITY,VDEC_EX_Field_Polarity);
    UADP_SPT_NAME0NXT(VDEC_EX_EXTERNAL_DS_BUF,VDEC_EX_EXTERNAL_DS_BUFFER);
    UADP_SPT_NAME0NXT(VDEC_EX_TIMEOUT_PARAM,VDEC_EX_Decode_Timeout_Param);
    UADP_SPT_NAME0NXT(VDEC_EX_ERR_TOLERANCE,VDEC_EX_Err_Tolerance);
    UADP_SPT_NAME0NXT(VDEC_EX_FRAME_PACKING_SIE,VDEC_EX_Frame_packing_SEI);
    UADP_SPT_NAME0NXT(VDEC_EX_VER_CTRL,VDEC_EX_Frame_packing_SEI_EX);
    UADP_SPT_NAME0NXT(VDEC_EX_CRC_VALUE,VDEC_EX_CrcValue);
    UADP_SPT_NAME0NXT(VDEC_EX_FRAME_INFO_EX,VDEC_EX_FrameInfoEX);
    UADP_SPT_NAME0NXT(VDEC_EX_STATUS,VDEC_EX_Status);
    UADP_SPT_NAME0NXT(VDEC_EX_CLOCK_SPEED,VDEC_EX_ClockSpeed);
    UADP_SPT_NAME0NXT(VDEC_EX_POWER_MODE,EN_POWER_MODE);
    UADP_SPT_NAME0NXT(VDEC_EX_DEC_MOD_CFG,VDEC_EX_DecModCfg);
    UADP_SPT_NAME0NXT(VDEC_EX_IAP_GnBufShareBWMode,VDEC_EX_IapGnBufShareBWMode);
    //E_VDEC_EX_V2_CMD_GET_FREE_STREAM_ID
    UADP_SPT_NAME6NXT(VDEC_EX_GET_FREE_STREAM_ID,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_STREAM_ID,param[1],VDEC_EX_U32,param[2],VDEC_EX_STREAM_TYPE,param[3],VDEC_EX_CODEC_TYPE,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_CMD_INIT
    UADP_SPT_NAME3NXT(VDEC_EX_INIT,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_INIT_PARAM,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_CMD_SET_CONTROL
    //E_VDEC_EX_V2_USER_CMD_CHECK_DISPINFO_READY:
    //E_VDEC_EX_V2_USER_CMD_PLAY:
    //E_VDEC_EX_V2_USER_CMD_PAUSE:
    //E_VDEC_EX_V2_USER_CMD_RESUME:
    //E_VDEC_EX_V2_USER_CMD_STEP_DISP:
    //E_VDEC_EX_V2_USER_CMD_STEP_DECODE:
    //E_VDEC_EX_V2_USER_CMD_FIRE_DEC:
    //E_VDEC_EX_V2_USER_CMD_MHEG_RST_IFRAME_DEC:
    //E_VDEC_EX_V2_USER_CMD_CC_STOP_PARSING:
    //E_VDEC_EX_V2_USER_CMD_RST:
    //E_VDEC_EX_V2_USER_CMD_EXIT:
    UADP_SPT_NAME2NXT(VDEC_EX_IO,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_SET_FRC_MODE
    UADP_SPT_NAME3NXT(VDEC_EX_SET_FRC_MODE,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_FRC_MODE,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_SET_DYNSCALING_PARAMS
    UADP_SPT_NAME4NXT(VDEC_EX_SET_DYNSCALING_PARAMS,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_ADDR ,param[1],VDEC_EX_U32,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_SET_DBG_LEVEL
    UADP_SPT_NAME3NXT(VDEC_EX_SET_DBG_LEVEL,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_DBG_LEVEL,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_SET_TRICK_MODE
    UADP_SPT_NAME3NXT(VDEC_EX_SET_TRICK_MODE,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_TRICK_DEC,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_PUSH_DECQ
    UADP_SPT_NAME3NXT(VDEC_EX_PUSH_DECQ,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_DEC_CMD,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_FLUSH
    UADP_SPT_NAME3NXT(VDEC_EX_FLUSH,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_FREEZE_PIC_SELECT,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_ENABLE_LAST_FRAME_SHOW:
    //E_VDEC_EX_V2_USER_CMD_SET_FREEZE_DISP:
    //E_VDEC_EX_V2_USER_CMD_SET_BLUE_SCREEN:
    //E_VDEC_EX_V2_USER_CMD_DISABLE_DEBLOCKING:
    //E_VDEC_EX_V2_USER_CMD_DISABLE_QUARTER_PIXEL:
    //E_VDEC_EX_V2_USER_CMD_SET_AUTO_RM_LST_ZERO_BYTE:
    //E_VDEC_EX_V2_USER_CMD_SET_BLOCK_DISPLAY:
    //E_VDEC_EX_V2_USER_CMD_ENABLE_ES_BUFF_MALLOC:
    UADP_SPT_NAME3NXT(VDEC_EX_IO_BOOL,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_BOOL,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_SET_SPEED
    UADP_SPT_NAME4NXT(VDEC_EX_SET_SPEED,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_SPEED_TYPE,param[1],VDEC_EX_SPEED,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_RESET_PTS:
    //E_VDEC_EX_V2_USER_CMD_AVSYNC_FREERUN_THRESHOLD:
    //E_VDEC_EX_V2_USER_CMD_SEEK_TO_PTS:
    //E_VDEC_EX_V2_USER_CMD_SKIP_TO_PTS:// TODO: what's the difference between skip & seek?
    //E_VDEC_EX_V2_USER_CMD_CC_INIT;
    UADP_SPT_NAME3NXT(VDEC_EX_IO_U32,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_U32,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_AVSYNC_ON
    UADP_SPT_NAME5NXT(VDEC_EX_AVSYNC_ON,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_BOOL,param[1],VDEC_EX_U32,param[2],VDEC_EX_SYNC_TOLERANCE,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_UNSET_EVENT_MULTICALLBACK
    UADP_SPT_NAME4NXT(VDEC_EX_UNSET_EVENT_MULTICALLBACK,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_TYPE,param[1],VDEC_EX_U32,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_SET_BALANCE_BW
    UADP_SPT_NAME6NXT(VDEC_EX_SET_BALANCE_BW,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_U8,param[1],VDEC_EX_U8,param[2],VDEC_EX_U8,param[3],VDEC_EX_U8,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GEN_PATTERN
    UADP_SPT_NAME5NXT(VDEC_EX_GEN_PATTERN,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_PATTERN_TYPE,param[1],VDEC_EX_ADDR,param[2],VDEC_EX_U32,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_MHEG_DECODE_IFRAME:
    UADP_SPT_NAME5NXT(VDEC_EX_MHEG_DECODE_IFRAME,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_ADDR,param[1],VDEC_EX_ADDR,param[2],VDEC_EX_ADDR,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_CC_START_PARSING:
    UADP_SPT_NAME3NXT(VDEC_EX_CC_START_PARSING,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_CC_CONFIG,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_DISPLAY_FRAME:
    UADP_SPT_NAME3NXT(VDEC_EX_DISP_RELEASE_FRAME,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_DISP_FRAME,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_CAPTURE_FRAME
    UADP_SPT_NAME4NXT(VDEC_EX_CAPTURE_FRAME,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_U32,param[1],VDEC_EX_BOOL,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_CC_SET_CFG:
    UADP_SPT_NAME5NXT(VDEC_EX_CC_SET_CFG,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_CC_FORMAT,param[1],VDEC_EX_CC_TYPE,param[2],VDEC_EX_CC_INPUT_PARAM,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_CC_SET_BUFF_START_ADDR
    //E_VDEC_EX_V2_USER_CMD_CC_UPDATE_WRITE_ADDR:
    //E_VDEC_EX_V2_USER_CMD_CC_UPDATE_READ_ADDR:
    UADP_SPT_NAME4NXT(VDEC_EX_CC_UPDATE_ADDR,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_CC_FORMAT,param[1],VDEC_EX_CC_INPUT_PARAM,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_CC_DISABLE_PARSING:
    //E_VDEC_EX_V2_USER_CMD_CC_GET_IS_RST_DONE
    UADP_SPT_NAME3NXT(VDEC_EX_CC_IO_CC_FORMAT,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_CC_FORMAT,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GETLIBVER:
    UADP_SPT_NAME3NXT(VDEC_EX_GET_LIBVER,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_MSIF_VERSION,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GETINFO:
    UADP_SPT_NAME3NXT(VDEC_EX_GET_INFO,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_INFO,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_CHECKCAPS
    UADP_SPT_NAME4NXT(VDEC_EX_CHECK_CAPS,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_CODEC_TYPE,param[1],VDEC_EX_BOOL,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_ACTIVE_CODEC_TYPE
    UADP_SPT_NAME3NXT(VDEC_EX_GET_ACTIVE_CODEC_TYPE,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_CODEC_TYPE,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_DISP_INFO:
    UADP_SPT_NAME3NXT(VDEC_EX_GET_DISP_INFO,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_DISP_INFO,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_EXT_DISP_INFO
    UADP_SPT_NAME3NXT(VDEC_EX_GET_EXT_DISP_INFO,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_EXT_DISP_INFO,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_DEC_FRAME_INFO
    UADP_SPT_NAME3NXT(VDEC_EX_GET_DEC_FRAME_INFO,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_FRAME_INFO,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_DEC_TIMECODE
    UADP_SPT_NAME3NXT(VDEC_EX_GET_DEC_TIMECODE,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_TIME_CODE,pRet,VDEC_EX_U32);

    //E_VDEC_EX_V2_USER_CMD_GET_COLOUR_PRIMARIES
    UADP_SPT_NAME3NXT(VDEC_EX_IO_U8,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_U8,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_FW_VERSION
    UADP_SPT_NAME4NXT(VDEC_EX_GET_FW_VERSION,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_FW_TYPE,param[1],VDEC_EX_U32,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_VIDEO_PTS_STC_DELTA
    UADP_SPT_NAME3NXT(VDEC_EX_SET_GET_U64,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_U64,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_ERR_CODE
    UADP_SPT_NAME3NXT(VDEC_EX_GET_ERR_CODE,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_ERR_CODE,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_CC_INFO
    UADP_SPT_NAME4NXT(VDEC_EX_GET_CC_INFO,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_CC_INFO,param[1],VDEC_EX_U32,pRet,VDEC_EX_U32);

    //E_VDEC_EX_V2_USER_CMD_GET_PATTERN_LEAST_LENGTH
    UADP_SPT_NAME4NXT(VDEC_EX_GET_PATTERN_LEAST_LENGTH,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_PATTERN_TYPE,param[1],VDEC_EX_U32,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_ES_BUFF
    UADP_SPT_NAME5NXT(VDEC_EX_GET_ES_BUFF,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_U32,param[1],VDEC_EX_U32,param[2],VDEC_EX_ADDR,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_CC_GET_INFO
    UADP_SPT_NAME5NXT(VDEC_EX_CC_GET_INFO,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_CC_FORMAT,param[1],VDEC_EX_CC_INFO_CMD,param[2],VDEC_EX_U32,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_CC_GET_WRITE_ADDR
    UADP_SPT_NAME4NXT(VDEC_EX_GET_CC_GET_RW_ADDR,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_CC_FORMAT,param[1],VDEC_EX_ADDR,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_FRC_OUTPUT
    UADP_SPT_NAME3NXT(VDEC_EX_FRC_OUTPUT,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_FRC_OUTPUT_PARAM,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_UT_SET_DBG_MODE
    UADP_SPT_NAME3NXT(VDEC_EX_UT_SET_DBG_MODE,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_DBG_MODE,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_FIELD_POLARITY_DISPLAY_ONE_FIELD
    UADP_SPT_NAME3NXT(VDEC_EX_FIELD_POLARITY_DISPLAY_ONE_FIELD,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_FIELD_POLARITY,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_SET_EXTERNAL_DS_BUFFER
    UADP_SPT_NAME3NXT(VDEC_EX_SET_EXTERNAL_DS_BUFFER,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_EXTERNAL_DS_BUF,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_ENABLE_DECODE_ENGINE_TIMEOUT
    UADP_SPT_NAME3NXT(VDEC_EX_ENABLE_DECODE_ENGINE_TIMEOUT,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_TIMEOUT_PARAM,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_SET_ERROR_TOLERANCE
    UADP_SPT_NAME3NXT(VDEC_EX_SET_ERROR_TOLERANCE,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_ERR_TOLERANCE,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_MAIN_STREAM_ID
    UADP_SPT_NAME3NXT(VDEC_EX_GET_STREAM_ID,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_STREAM_ID,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_FPA_SEI
    UADP_SPT_NAME3NXT(VDEC_EX_GET_FPA_SEI,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_FRAME_PACKING_SIE,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_FPA_SEI_EX
    UADP_SPT_NAME3NXT(VDEC_EX_GET_FPA_SEI_EX,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_VER_CTRL,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_CRC_VALUE
    UADP_SPT_NAME3NXT(VDEC_EX_GET_CRC_VALUE,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_CRC_VALUE,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_FRAME_INFO_EX:
    UADP_SPT_NAME3NXT(VDEC_EX_GET_FRAME_INFO_EX,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_FRAME_INFO_EX,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_PREGETSTATUS
    UADP_SPT_NAME3NXT(VDEC_EX_PREGETSTATUS,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_STATUS,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_SYSTEM_PRESET_VPU_CLOCK
    UADP_SPT_NAME3NXT(VDEC_EX_SYSTEM_PRESET_CLOCK,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_CLOCK_SPEED,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_SETPOWERSTATE
    UADP_SPT_NAME3NXT(VDEC_EX_SET_POWERSTATE,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_POWER_MODE,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_PRESET_DECODE_MODE

    UADP_SPT_NAME1NXT(VDEC_EX_PTR_DEC_MOD_CFG,VDEC_EX_PtrDecModCfg,pVDEC_EX_DecModCfg,VDEC_EX_DEC_MOD_CFG);
    UADP_SPT_NAME3NXT(VDEC_EX_PRESET_DECODE_MODE,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_PTR_DEC_MOD_CFG,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_HVD_IAPGN_BUF_SHARE_BW_MODE

    UADP_SPT_NAME1NXT(VDEC_EX_PTR_IAP_GnBufShareBWMode,VDEC_EX_PtrIapGnBufShareBWMode,pVDEC_EX_IapGnBufShareBWMode,VDEC_EX_IAP_GnBufShareBWMode);
    UADP_SPT_NAME3NXT(VDEC_EX_HVD_IAPGN_BUF_SHARE_BW_MODE,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_PTR_IAP_GnBufShareBWMode,pRet,VDEC_EX_U32);
    //E_VDEC_EX_V2_USER_CMD_GET_EVENT_FLAG
    UADP_SPT_NAME4NXT(VDEC_EX_GET_EVENT_FLAG,VDEC_EX_V2_IO_Param,StreamID,VDEC_EX_STREAM_V2_ID,param[0],VDEC_EX_U32,param[1],VDEC_EX_U32,pRet,VDEC_EX_U32);

    *pIoctl= (FUtopiaIOctl)VDEC_EX_adp_Ioctl;

    return 0;
}


MS_U32 VDEC_EX_adp_Ioctl(void* pInstanceTmp, MS_U32 u32Cmd, void* const pArgs)
{
    MS_U32 u32Ret = UTOPIA_STATUS_SUCCESS;
    char buffer_arg[128];

    VDEC_EX_V2_IO_Param Kernel_AccessUser_Param;
    VDEC_EX_V2_IO_Param Kernel_IO_param;
    VDEC_EX_V2_StreamId StreamID;
    VDEC_EX_V2_Result vRet;
    VDEC_EX_V2_IO_Param* user_IO_Param = pArgs;
    VDEC_EX_V2_IO_Param* kernel_user_IO_Param = &Kernel_AccessUser_Param;
    VDEC_EX_V2_IO_Param* kernel_IO_Param = &Kernel_IO_param;
    kernel_IO_Param->StreamID = (&StreamID);
    kernel_IO_Param->pRet = (&vRet);
    //unsigned char* karg = NULL;
    MS_PHYADDR u32Addr = 0;
    VDEC_EX_V2_TrickDec eTrickDec = E_VDEC_EX_V2_TRICK_DEC_ALL;
    VDEC_EX_V2_CodecType eCodecType = E_VDEC_EX_V2_CODEC_TYPE_NONE;
    VDEC_EX_V2_PatternType ePattern = E_VDEC_EX_V2_PATTERN_FLUSH;
    VDEC_EX_V2_CCFormat eCCFormat = E_VDEC_EX_V2_CC_NONE;
    VDEC_EX_V2_DispInfo stDispInfo;
    VDEC_EX_V2_CC_Info stCCInfo;
    MS_BOOL bEnable = 0 ;
    MS_U32 u32Param0 = 0,u32Param1 = 0,u32Param2 = 0;
    MS_U16 u16Param0 = 0;
    MS_U8 u8Param0 = 0;
    MS_U64 u64Param0 = 0;

    if (u32Cmd >= E_VDEC_EX_V2_CMD_MAX) return -ENOTTY;
	
    if (!access_ok(VERIFY_WRITE, (void *)pArgs, sizeof(*pArgs)))
    {
        printk("[%s] with bad address with cmd 0x%lx!\n", __func__, u32Cmd);
        return -EFAULT;
    }
	
    switch(u32Cmd)
    {
        case E_VDEC_EX_V2_CMD_GET_FREE_STREAM_ID:
            u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FREE_STREAM_ID, spt_VDEC_EX_GET_FREE_STREAM_ID,buffer_arg,sizeof(buffer_arg));
            break;
        case E_VDEC_EX_V2_CMD_INIT:
            u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_INIT, spt_VDEC_EX_INIT,buffer_arg,sizeof(buffer_arg));
            break;
        case E_VDEC_EX_V2_CMD_SET_CONTROL:
            CPY_FROM_USER((void*)kernel_user_IO_Param, (VDEC_EX_V2_IO_Param*)pArgs, sizeof(VDEC_EX_V2_IO_Param));
            kernel_IO_Param->eUserCmd = kernel_user_IO_Param->eUserCmd;

            switch(kernel_IO_Param->eUserCmd)
            {
                case E_VDEC_EX_V2_USER_CMD_CHECK_DISPINFO_READY:
                case E_VDEC_EX_V2_USER_CMD_PLAY:
                case E_VDEC_EX_V2_USER_CMD_PAUSE:
                case E_VDEC_EX_V2_USER_CMD_RESUME:
                case E_VDEC_EX_V2_USER_CMD_STEP_DISP:
                case E_VDEC_EX_V2_USER_CMD_STEP_DECODE:
                case E_VDEC_EX_V2_USER_CMD_FIRE_DEC:
                case E_VDEC_EX_V2_USER_CMD_MHEG_RST_IFRAME_DEC:
                case E_VDEC_EX_V2_USER_CMD_CC_STOP_PARSING:
                case E_VDEC_EX_V2_USER_CMD_RST:
                case E_VDEC_EX_V2_USER_CMD_EXIT:
                case E_VDEC_EX_V2_USER_CMD_DROP_ONE_PTS:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO, spt_VDEC_EX_IO,buffer_arg,sizeof(buffer_arg));
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_FRC_MODE:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_FRC_MODE, spt_VDEC_EX_SET_FRC_MODE,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_FrcMode eFrcMode;
                        kernel_IO_Param->param[0] = (void*)(&eFrcMode);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_V2_FrcMode));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_DYNSCALING_PARAMS:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_DYNSCALING_PARAMS, spt_VDEC_EX_SET_DYNSCALING_PARAMS,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&u32Addr);
                    kernel_IO_Param->param[1] = (void*)(&u32Param0);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(MS_PHYADDR));
                    copy_from_user((void*)kernel_IO_Param->param[1],(void*)kernel_user_IO_Param->param[1],sizeof(MS_U32));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_DBG_LEVEL:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_DBG_LEVEL, spt_VDEC_EX_SET_DBG_LEVEL,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_DbgLevel eDbglevel;
                        kernel_IO_Param->param[0] = (void*)(&eDbglevel);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_V2_DbgLevel));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_TRICK_MODE:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_TRICK_MODE, spt_VDEC_EX_SET_TRICK_MODE,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&eTrickDec);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_V2_TrickDec));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_PUSH_DECQ:
                case E_VDEC_EX_V2_USER_CMD_MVC_BBU2_PUSH_PACKET:
                case E_VDEC_EX_V2_USER_CMD_MVC_BBU2_FIRE_DECCMD:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_PUSH_DECQ, spt_VDEC_EX_PUSH_DECQ,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_DecCmd eVdecCmd;
                        kernel_IO_Param->param[0] = (void*)(&eVdecCmd);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_V2_DecCmd));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_FLUSH:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_FLUSH, spt_VDEC_EX_FLUSH,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_FreezePicSelect eVFreezePic;
                        kernel_IO_Param->param[0] = (void*)(&eVFreezePic);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_V2_FreezePicSelect));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_ENABLE_LAST_FRAME_SHOW:
                case E_VDEC_EX_V2_USER_CMD_SET_FREEZE_DISP:
                case E_VDEC_EX_V2_USER_CMD_SET_BLUE_SCREEN:
                case E_VDEC_EX_V2_USER_CMD_DISABLE_DEBLOCKING:
                case E_VDEC_EX_V2_USER_CMD_DISABLE_QUARTER_PIXEL:
                case E_VDEC_EX_V2_USER_CMD_SET_AUTO_RM_LST_ZERO_BYTE:
                case E_VDEC_EX_V2_USER_CMD_SET_BLOCK_DISPLAY:
                case E_VDEC_EX_V2_USER_CMD_ENABLE_ES_BUFF_MALLOC:
                case E_VDEC_EX_V2_USER_CMD_REPEAT_LAST_FIELD:
                case E_VDEC_EX_V2_USER_CMD_FAST_DISPLAY:
                case E_VDEC_EX_V2_USER_CMD_IGNORE_ERR_REF:
                case E_VDEC_EX_V2_USER_CMD_FORCE_FOLLOW_DTV_SPEC:
                case E_VDEC_EX_V2_USER_CMD_DISABLE_SEQ_CHG:
                case E_VDEC_EX_V2_USER_CMD_DTV_RESET_MVD_PARSER:
                case E_VDEC_EX_V2_USER_CMD_SET_DISP_OUTSIDE_CTRL_MODE:
                case E_VDEC_EX_V2_USER_CMD_RELEASE_FD_MASK:
                case E_VDEC_EX_V2_USER_CMD_FLUSH_PTS_BUF:
                case E_VDEC_EX_V2_USER_CMD_SUPPORT_AVC_TO_MVC:
                case E_VDEC_EX_V2_USER_CMD_3DLR_VIEW_EXCHANGE:
                case E_VDEC_EX_V2_USER_CMD_AVC_NEW_SLOW_MOTION:
                case E_VDEC_EX_V2_USER_CMD_SET_VSIZE_ALIGN:
                case E_VDEC_EX_V2_USER_CMD_SHOW_DECODE_ORDER:
                case E_VDEC_EX_V2_USER_CMD_AVC_DISP_IGNORE_CROP:
                case E_VDEC_EX_V2_USER_CMD_SUSPEND_DYNAMIC_SCALE:
                case E_VDEC_EX_V2_USER_CMD_FORCE_AUTO_MUTE:
                case E_VDEC_EX_V2_USER_CMD_SET_DISP_FINISH_MODE:
                case E_VDEC_EX_V2_USER_CMD_SET_AVSYNC_MODE:
                case E_VDEC_EX_V2_USER_CMD_PUSH_DISPQ_WITH_REF_NUM:
                case E_VDEC_EX_V2_USER_CMD_DS_RESV_N_BUFFER:
                case E_VDEC_EX_V2_USER_CMD_RM_ENABLE_PTS_TBL:
                case E_VDEC_EX_V2_USER_CMD_SET_CC608_INFO_ENHANCE_MODE:
                case E_VDEC_EX_V2_USER_CMD_IGNORE_PIC_OVERRUN:
                case E_VDEC_EX_V2_USER_CMD_CTL_SPEED_IN_DISP_ONLY:
                case E_VDEC_EX_V2_USER_CMD_AVC_SUPPORT_REF_NUM_OVER_MAX_DPB_SIZE:
                case E_VDEC_EX_V2_USER_CMD_AVC_FORCE_BROKEN_BY_US:
                case E_VDEC_EX_V2_USER_CMD_DUAL_NON_BLOCK_MODE:
                case E_VDEC_EX_V2_USER_CMD_FRAMEBUFFER_AUTO_MODE:
                case E_VDEC_EX_V2_USER_CMD_SET_PTS_US_MODE:
                case E_VDEC_EX_V2_USER_CMD_AUTO_INSERT_DUMMY_DATA:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_BOOL, spt_VDEC_EX_IO_BOOL,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&bEnable);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(MS_BOOL));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_SPEED:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_SPEED, spt_VDEC_EX_SET_SPEED,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_SpeedType eSpeedType;
                        VDEC_EX_V2_DispSpeed eDispSpeed;
                        kernel_IO_Param->param[0] = (void*)(&eSpeedType);
                        kernel_IO_Param->param[1] = (void*)(&eDispSpeed);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_V2_SpeedType));
                        copy_from_user((void*)kernel_IO_Param->param[1],(void*)kernel_user_IO_Param->param[1],sizeof(VDEC_EX_V2_DispSpeed));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_RESET_PTS:
                case E_VDEC_EX_V2_USER_CMD_AVSYNC_FREERUN_THRESHOLD:
                case E_VDEC_EX_V2_USER_CMD_SEEK_TO_PTS:
                case E_VDEC_EX_V2_USER_CMD_SKIP_TO_PTS:
                case E_VDEC_EX_V2_USER_CMD_CC_INIT:
                case E_VDEC_EX_V2_USER_CMD_AVSYNC_REPEAT_TH:
                case E_VDEC_EX_V2_USER_CMD_DISP_ONE_FIELD:
                case E_VDEC_EX_V2_USER_CMD_FD_MASK_DELAY_COUNT:
                case E_VDEC_EX_V2_USER_CMD_FRC_DROP_TYPE:
                case E_VDEC_EX_V2_USER_CMD_AVC_MIN_FRM_GAP:
                case E_VDEC_EX_V2_USER_CMD_FORCE_INTERLACE_MODE:
                case E_VDEC_EX_V2_USER_CMD_SET_DTV_USER_DATA_MODE:
                case E_VDEC_EX_V2_USER_CMD_AUTO_EXHAUST_ES_MODE:
                case E_VDEC_EX_V2_USER_CMD_SHOW_FIRST_FRAME_DIRECT:
                case E_VDEC_EX_V2_USER_CMD_AVC_RESIZE_DOS_DISP_PEND_BUF:
                case E_VDEC_EX_V2_USER_CMD_SET_XC_LOW_DELAY_PARA:
                case E_VDEC_EX_V2_USER_CMD_SET_SECURE_MODE:
                case E_VDEC_EX_V2_USER_CMD_FRAMERATE_HANDLING:
                case E_VDEC_EX_V2_USER_CMD_RVU_SETTING_MODE:
                case E_VDEC_EX_V2_USER_CMD_IGNORE_PIC_STRUCT_DISPLAY:
                case E_VDEC_EX_V2_USER_CMD_INPUT_PTS_FREERUN_MODE:
                case E_VDEC_EX_V2_USER_CMD_ERR_CONCEAL_SLICE_1ST_MB:
                case E_VDEC_EX_V2_USER_CMD_SET_MIN_TSP_DATA_SIZE:
                case E_VDEC_EX_V2_USER_CMD_SET_DMX_FRAMERATE:
                case E_VDEC_EX_V2_USER_CMD_SET_DMX_FRAMERATEBASE:
                case E_VDEC_EX_V2_USER_CMD_ENABLE_CC_608_EXTERNAL_BUFFER:
                case E_VDEC_EX_V2_USER_CMD_ENABLE_CC_708_EXTERNAL_BUFFER:
                case E_VDEC_EX_V2_USER_CMD_SET_TIME_INC_PREDICT_PARA:
                case E_VDEC_EX_V2_USER_CMD_PVR_TIMESHIFT_SEAMLESS_MODE:
                case E_VDEC_EX_V2_USER_CMD_RETURN_INVALID_AFD:
                case E_VDEC_EX_V2_USER_CMD_PTS_DISCONTINUE_AUTO_DETECT:
                case E_VDEC_EX_V2_USER_CMD_ENABLE_PTS_DECTECTOR:
                case E_VDEC_EX_V2_USER_CMD_SET_AVSYNC_DISP_AUTO_DROP:
                //case E_VDEC_EX_V2_USER_CMD_DISABLE_DIVX:
                case E_VDEC_EX_V2_USER_CMD_SET_PUSI_SETTING:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_U32, spt_VDEC_EX_IO_U32,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&u32Param0);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(MS_U32));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_DYNAMIC_DISP_PATH:
                    if(1)
                    {
                        VDEC_EX_DynmcDispPath stDynmcDispPath;
                        kernel_IO_Param->param[0] = (void*)(&stDynmcDispPath);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_DynmcDispPath));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_GST_TIMING:
                    if(1)
                    {
                        VDEC_EX_MVOPInfo stMVOPInfo;
                        kernel_IO_Param->param[0] = (void*)(&stMVOPInfo);//kmalloc(sizeof(VDEC_EX_V2_FrameInfoEX),GFP_KERNEL);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_MVOPInfo));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_AVSYNC_ON:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_AVSYNC_ON, spt_VDEC_EX_AVSYNC_ON,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&bEnable);
                    kernel_IO_Param->param[1] = (void*)(&u32Param0);
                    kernel_IO_Param->param[2] = (void*)(&u16Param0);;
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(MS_BOOL));
                    copy_from_user((void*)kernel_IO_Param->param[1],(void*)kernel_user_IO_Param->param[1],sizeof(MS_U32));
                    copy_from_user((void*)kernel_IO_Param->param[2],(void*)kernel_user_IO_Param->param[2],sizeof(MS_U16));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_EVENT_MULTICALLBACK:
                case E_VDEC_EX_V2_USER_CMD_UNSET_EVENT_MULTICALLBACK:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_UNSET_EVENT_MULTICALLBACK, spt_VDEC_EX_UNSET_EVENT_MULTICALLBACK,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_BALANCE_BW:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_BALANCE_BW, spt_VDEC_EX_SET_BALANCE_BW,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GEN_PATTERN:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GEN_PATTERN, spt_VDEC_EX_GEN_PATTERN,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_MHEG_DECODE_IFRAME:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_MHEG_DECODE_IFRAME, spt_VDEC_EX_MHEG_DECODE_IFRAME,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_CC_START_PARSING:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_CC_START_PARSING, spt_VDEC_EX_CC_START_PARSING,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_DISPLAY_FRAME:
                case E_VDEC_EX_V2_USER_CMD_RELEASE_FRAME:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_DISP_RELEASE_FRAME, spt_VDEC_EX_DISP_RELEASE_FRAME,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_CAPTURE_FRAME:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_CAPTURE_FRAME, spt_VDEC_EX_CAPTURE_FRAME,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_CC_SET_CFG:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_CC_SET_CFG, spt_VDEC_EX_CC_SET_CFG,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_CC_SET_BUFF_START_ADDR:
                case E_VDEC_EX_V2_USER_CMD_CC_UPDATE_WRITE_ADDR:
                case E_VDEC_EX_V2_USER_CMD_CC_UPDATE_READ_ADDR:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_CC_UPDATE_ADDR, spt_VDEC_EX_CC_UPDATE_ADDR,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_CC_DISABLE_PARSING:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_CC_IO_CC_FORMAT, spt_VDEC_EX_CC_IO_CC_FORMAT,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_FRC_OUTPUT:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_FRC_OUTPUT, spt_VDEC_EX_FRC_OUTPUT,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_UT_SET_DBG_MODE:
                case E_VDEC_EX_V2_USER_CMD_UT_CLR_DBG_MODE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_UT_SET_DBG_MODE, spt_VDEC_EX_UT_SET_DBG_MODE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_IDCT_MODE:
                case E_VDEC_EX_V2_USER_CMD_DROP_ERR_FRAME:
                case E_VDEC_EX_V2_USER_CMD_SET_SELF_SEQCHANGE:
                case E_VDEC_EX_V2_USER_CMD_SET_SMOOTH_REWIND:
                case E_VDEC_EX_V2_USER_CMD_SET_MBX_PARAM:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_U8, spt_VDEC_EX_IO_U8,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_FIELD_POLARITY_DISPLAY_ONE_FIELD:
                    if(1)
                    {
                        VDEC_EX_Field_Polarity stVDECFieldPolarity;
                        kernel_IO_Param->param[0] = (void*)(&stVDECFieldPolarity);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_Field_Polarity));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));   
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_EXTERNAL_DS_BUFFER:
                    if(1)
                    {
                        VDEC_EX_EXTERNAL_DS_BUFFER stVDEC_DS_buff;
                        kernel_IO_Param->param[0] = (void*)(&stVDEC_DS_buff);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_EXTERNAL_DS_BUFFER));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_ENABLE_DECODE_ENGINE_TIMEOUT:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_ENABLE_DECODE_ENGINE_TIMEOUT, spt_VDEC_EX_ENABLE_DECODE_ENGINE_TIMEOUT,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_ERROR_TOLERANCE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_ERROR_TOLERANCE, spt_VDEC_EX_SET_ERROR_TOLERANCE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SET_FRAMEBUFF2:
                    if(1)
                    {
                        #if 0
                        kernel_IO_Param->param[0] = (void*)(&u32Param0);
                        kernel_IO_Param->param[1] = (void*)(&u32Param1);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)user_IO_Param->param[0],sizeof(MS_U32));
                        copy_from_user((void*)kernel_IO_Param->param[1],(void*)user_IO_Param->param[1],sizeof(MS_U32));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                        #else
                        VDEC_FRAMEBuff stframebuff;
                        kernel_IO_Param->param[0] = (void*)(&stframebuff);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_FRAMEBuff));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                        #endif
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_PVR_FLUSH_FRAME_BUFFER:
                case E_VDEC_EX_V2_USER_CMD_AVC_DISABLE_ANTI_VDEAD:
                case E_VDEC_EX_V2_USER_CMD_CC_GET_WRITE_PTR://unused
                case E_VDEC_EX_V2_USER_CMD_CC_GET_READ_PTR:
                case E_VDEC_EX_V2_USER_CMD_CC_UPDATE_READ_PTR:
                default:
                    break;
            }

            break;
        case E_VDEC_EX_V2_CMD_GET_CONTROL:
            CPY_FROM_USER((void*)kernel_user_IO_Param, pArgs, sizeof(VDEC_EX_V2_IO_Param));
            kernel_IO_Param->eUserCmd = kernel_user_IO_Param->eUserCmd;

            switch(kernel_IO_Param->eUserCmd)
            {
                case E_VDEC_EX_V2_USER_CMD_GETLIBVER:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_LIBVER, spt_VDEC_EX_GET_LIBVER,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GETINFO:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_INFO, spt_VDEC_EX_GET_INFO,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_CHECKCAPS:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_CHECK_CAPS, spt_VDEC_EX_CHECK_CAPS,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&eCodecType);//kmalloc(sizeof(MS_U32),GFP_KERNEL);
                    kernel_IO_Param->param[1] = (void*)(&bEnable);//kmalloc(sizeof(MS_U32),GFP_KERNEL);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_V2_CodecType));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->param[1],(void*)kernel_IO_Param->param[1],sizeof(MS_BOOL));
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_ACTIVE_CODEC_TYPE:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_ACTIVE_CODEC_TYPE, spt_VDEC_EX_GET_ACTIVE_CODEC_TYPE,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&eCodecType);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_CodecType));
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_IS_STEP_DISP_DONE:
                case E_VDEC_EX_V2_USER_CMD_IS_STEP_DECODE_DONE:
                case E_VDEC_EX_V2_USER_CMD_IS_DISP_FINISH:
                case E_VDEC_EX_V2_USER_CMD_IS_AVSYNC_ON:
                case E_VDEC_EX_V2_USER_CMD_IS_WITH_VALID_STREAM:
                case E_VDEC_EX_V2_USER_CMD_IS_IFRAME_FOUND:
                case E_VDEC_EX_V2_USER_CMD_IS_SEQ_CHG:
                case E_VDEC_EX_V2_USER_CMD_IS_REACH_SYNC:
                case E_VDEC_EX_V2_USER_CMD_IS_START_SYNC:
                case E_VDEC_EX_V2_USER_CMD_IS_FREERUN:
                case E_VDEC_EX_V2_USER_CMD_IS_WITH_LOW_DELAY:
                case E_VDEC_EX_V2_USER_CMD_IS_ALL_BUFFER_EMPTY:
                case E_VDEC_EX_V2_USER_CMD_IS_FRAME_RDY:
                case E_VDEC_EX_V2_USER_CMD_IS_ALIVE:
                case E_VDEC_EX_V2_USER_CMD_MHEG_IS_IFRAME_DECODING:
                case E_VDEC_EX_V2_USER_CMD_GET_IS_STR_RESUME:
                case E_VDEC_EX_V2_USER_CMD_GET_IS_STR:
                case E_VDEC_EX_V2_USER_CMD_GET_IS_SEAMLESS_MODE:
                case E_VDEC_EX_V2_USER_CMD_IS_MORE_FRAME:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO, spt_VDEC_EX_IO,buffer_arg,sizeof(buffer_arg));
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_DECQ_VACANCY:
                case E_VDEC_EX_V2_USER_CMD_GET_ES_WRITE_PTR:
                case E_VDEC_EX_V2_USER_CMD_GET_ES_READ_PTR:
                case E_VDEC_EX_V2_USER_CMD_GET_PTS:
                case E_VDEC_EX_V2_USER_CMD_GET_NEXT_PTS:
                case E_VDEC_EX_V2_USER_CMD_GET_ERR_CNT:
                case E_VDEC_EX_V2_USER_CMD_GET_BITRATE:
                case E_VDEC_EX_V2_USER_CMD_GET_FRAME_CNT:
                case E_VDEC_EX_V2_USER_CMD_GET_SKIP_CNT:
                case E_VDEC_EX_V2_USER_CMD_GET_DROP_CNT:
                case E_VDEC_EX_V2_USER_CMD_GET_DISP_CNT:
                case E_VDEC_EX_V2_USER_CMD_GET_ES_BUFF_VACANCY:
                case E_VDEC_EX_V2_USER_CMD_GET_CHROMA_TYPE:
                case E_VDEC_EX_V2_USER_CMD_GET_REAL_FRAMERATE:
                case E_VDEC_EX_V2_USER_CMD_GET_ES_QUANTITY:
                case E_VDEC_EX_V2_USER_CMD_GET_COLOR_MATRIX:
                case E_VDEC_EX_V2_USER_CMD_GET_DYNSCALE_ENABLED:
                case E_VDEC_EX_V2_USER_CMD_GET_ES2_QUANTITY:
                case E_VDEC_EX_V2_USER_CMD_GET_MVC_BBU2_DECQ_VACANCY:
                case E_VDEC_EX_V2_USER_CMD_GET_MVC_ES2_READ_PTR:
                case E_VDEC_EX_V2_USER_CMD_GET_MVC_ES2_WRITE_PTR:
                case E_VDEC_EX_V2_USER_CMD_GET_ORI_INTERLACE_MODE:
                case E_VDEC_EX_V2_USER_CMD_GET_MBS_ONLY_FLAG:
                case E_VDEC_EX_V2_USER_CMD_GET_BBU_Q_NUM:
                case E_VDEC_EX_V2_USER_CMD_GET_DISP_FRAME_NUM:
                case E_VDEC_EX_V2_USER_CMD_GET_ES_BUFFER_STATUS:
                case E_VDEC_EX_V2_USER_CMD_GET_CODEC_TYPE:
                case E_VDEC_EX_V2_USER_CMD_GET_SHAREMEMORY_BASE:
                case E_VDEC_EX_V2_USER_CMD_GET_XC_LOW_DELAY_INT_STATE:
                case E_VDEC_EX_V2_USER_CMD_GET_IS_LEAST_DISPQ_SIZE_FLAG:
                case E_VDEC_EX_V2_USER_CMD_GET_FIELD_PIC_FLAG:
                case E_VDEC_EX_V2_USER_CMD_GET_VSYNC_BRIDGE_ADDR:
                case E_VDEC_EX_V2_USER_CMD_GET_EVENT_INFO:
                case E_VDEC_EX_V2_USER_CMD_GET_FLUSH_PATTEN_ENTRY_NUM:
                case E_VDEC_EX_V2_USER_CMD_GET_DS_BUF_MIU_SEL:
                case E_VDEC_EX_V2_USER_CMD_GET_FW_STATUS_FLAG:
                case E_VDEC_EX_V2_USER_CMD_GET_HW_MAX_PIXEL:
                case E_VDEC_EX_V2_USER_CMD_GET_VSYNC_BRIDGE_EXT_ADDR:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_U32, spt_VDEC_EX_IO_U32,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&u32Param0);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(MS_U32));
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_EVENT_FLAG:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_EVENT_FLAG, spt_VDEC_EX_GET_EVENT_FLAG,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&u32Param0);//kmalloc(sizeof(MS_U32),GFP_KERNEL);
                    kernel_IO_Param->param[1] = (void*)(&u32Param1);//kmalloc(sizeof(MS_U32),GFP_KERNEL);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    copy_from_user((void*)kernel_IO_Param->param[1],(void*)kernel_user_IO_Param->param[1],sizeof(MS_U32));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(MS_U32));
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_DISP_INFO:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_DISP_INFO, spt_VDEC_EX_GET_DISP_INFO,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&stDispInfo);//;kmalloc(sizeof(VDEC_EX_V2_DispInfo),GFP_KERNEL);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    //copy_from_user((void*)kernel_IO_Param->param[0],(void*)user_IO_Param->param[0],sizeof(VDEC_EX_V2_DispInfo));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_DispInfo));
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_EXT_DISP_INFO:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_EXT_DISP_INFO, spt_VDEC_EX_GET_EXT_DISP_INFO,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_ExtDispInfo stExtDispInfo;
                        kernel_IO_Param->param[0] = (void*)(&stExtDispInfo);//kmalloc(sizeof(VDEC_EX_V2_ExtDispInfo),GFP_KERNEL);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_ExtDispInfo));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_DEC_FRAME_INFO:
                case E_VDEC_EX_V2_USER_CMD_GET_DISP_FRAME_INFO:
                case E_VDEC_EX_V2_USER_CMD_GET_MVC_SUB_FRAME_DISP_INFO:
                case E_VDEC_EX_V2_USER_CMD_GET_SIMPLE_FRAME:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_DEC_FRAME_INFO, spt_VDEC_EX_GET_DEC_FRAME_INFO,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_FrameInfo stFrameInfo;
                        kernel_IO_Param->param[0] = (void*)(&stFrameInfo);//kmalloc(sizeof(VDEC_EX_V2_FrameInfo),GFP_KERNEL);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        //copy_from_user((void*)kernel_IO_Param->param[0],(void*)user_IO_Param->param[0],sizeof(VDEC_EX_V2_FrameInfo));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_FrameInfo));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_DEC_TIMECODE:
                case E_VDEC_EX_V2_USER_CMD_GET_DISP_TIMECODE:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_DEC_TIMECODE, spt_VDEC_EX_GET_DEC_TIMECODE,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_TimeCode stTimeCode;
                        kernel_IO_Param->param[0] = (void*)(&stTimeCode);//kmalloc(sizeof(MS_U64),GFP_KERNEL);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_TimeCode));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_COLOUR_PRIMARIES:
                case E_VDEC_EX_V2_USER_CMD_GET_GOP_CNT:
                case E_VDEC_EX_V2_USER_CMD_GET_HW_KEY:
                case E_VDEC_EX_V2_USER_CMD_GET_ACTIVE_FORMAT:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_U8, spt_VDEC_EX_IO_U8,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&u8Param0);//kmalloc(sizeof(MS_U64),GFP_KERNEL);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(MS_U8));
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_FW_VERSION:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FW_VERSION, spt_VDEC_EX_GET_FW_VERSION,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_FwType eFwType;
                        kernel_IO_Param->param[0] = (void*)(&eFwType);
                        kernel_IO_Param->param[1] = (void*)(&u32Param0);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_V2_FwType));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[1],(void*)kernel_IO_Param->param[1],sizeof(MS_U32));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_VIDEO_PTS_STC_DELTA:
                case E_VDEC_EX_V2_USER_CMD_GET_U64PTS:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_GET_U64, spt_VDEC_EX_SET_GET_U64,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&u64Param0);//kmalloc(sizeof(MS_U64),GFP_KERNEL);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(MS_U64));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(MS_U64));
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_ERR_CODE:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_ERR_CODE, spt_VDEC_EX_GET_ERR_CODE,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_ErrCode eErrCode;
                        kernel_IO_Param->param[0] = (void*)(&eErrCode);//kmalloc(sizeof(MS_U64),GFP_KERNEL);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_ErrCode));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_IS_32_PULLDOWN:
                case E_VDEC_EX_V2_USER_CMD_IS_CC_AVAILABLE:
                case E_VDEC_EX_V2_USER_CMD_CC_GET_IS_OVERFLOW:
                case E_VDEC_EX_V2_USER_CMD_GET_SUPPORT_2ND_MVOP_INTERFACE:
                case E_VDEC_EX_V2_USER_CMD_GET_SECURE_MODE:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_BOOL, spt_VDEC_EX_IO_BOOL,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&bEnable);//kmalloc(sizeof(MS_U64),GFP_KERNEL);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(MS_BOOL));
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_CC_INFO:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_CC_INFO, spt_VDEC_EX_GET_CC_INFO,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&stCCInfo);//kmalloc(sizeof(VDEC_EX_V2_CC_Info),GFP_KERNEL);
                    kernel_IO_Param->param[1] = (void*)(&u32Param0);//kmalloc(sizeof(MS_U32),GFP_KERNEL);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_V2_CC_Info));
                    copy_from_user((void*)kernel_IO_Param->param[1],(void*)kernel_user_IO_Param->param[1],sizeof(MS_U32));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_CC_Info));
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_TRICK_MODE:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_TRICK_MODE, spt_VDEC_EX_SET_TRICK_MODE,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&eTrickDec);//kmalloc(sizeof(MS_U64),GFP_KERNEL);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_TrickDec));
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_PATTERN_LEAST_LENGTH:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_PATTERN_LEAST_LENGTH, spt_VDEC_EX_GET_PATTERN_LEAST_LENGTH,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&ePattern);//kmalloc(sizeof(VDEC_EX_V2_CC_Info),GFP_KERNEL);
                    kernel_IO_Param->param[1] = (void*)(&u32Param0);//kmalloc(sizeof(MS_U32),GFP_KERNEL);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_V2_PatternType));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->param[1],(void*)kernel_IO_Param->param[1],sizeof(MS_U32));
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_ES_BUFF:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_ES_BUFF, spt_VDEC_EX_GET_ES_BUFF,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&u32Param0);//kmalloc(sizeof(MS_U32),GFP_KERNEL);
                    kernel_IO_Param->param[1] = (void*)(&u32Param1);//kmalloc(sizeof(MS_U32),GFP_KERNEL);
                    kernel_IO_Param->param[2] = (void*)(&u32Param2);//kmalloc(sizeof(MS_U32),GFP_KERNEL);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(MS_U32));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->param[1],(void*)kernel_IO_Param->param[1],sizeof(MS_U32));
                    copy_to_user((void*)kernel_user_IO_Param->param[2],(void*)kernel_IO_Param->param[2],sizeof(MS_U32));
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_NEXT_DISP_FRAME:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_DISP_RELEASE_FRAME, spt_VDEC_EX_DISP_RELEASE_FRAME,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_DispFrame stDispFrame;
                        kernel_IO_Param->param[0] = (void*)(&stDispFrame);//kmalloc(sizeof(VDEC_EX_V2_DispFrame),GFP_KERNEL);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_DispFrame));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_CC_GET_INFO:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_CC_GET_INFO, spt_VDEC_EX_CC_GET_INFO,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_CCInfoCmd eCCInfo;
                        kernel_IO_Param->param[0] = (void*)(&eCCFormat);//kmalloc(sizeof(VDEC_EX_V2_CCFormat),GFP_KERNEL);
                        kernel_IO_Param->param[1] = (void*)(&eCCInfo);//kmalloc(sizeof(VDEC_EX_V2_CCInfoCmd),GFP_KERNEL);
                        kernel_IO_Param->param[2] = (void*)(&u32Param0);//kmalloc(sizeof(MS_U32),GFP_KERNEL);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_V2_CCFormat));
                        copy_from_user((void*)kernel_IO_Param->param[1],(void*)kernel_user_IO_Param->param[1],sizeof(VDEC_EX_V2_CCInfoCmd));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[2],(void*)kernel_IO_Param->param[2],sizeof(MS_U32));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_CC_GET_IS_RST_DONE:
                case E_VDEC_EX_V2_USER_CMD_CC_GET_IS_BUFF_OVERFLOW:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_CC_IO_CC_FORMAT, spt_VDEC_EX_CC_IO_CC_FORMAT,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&eCCFormat);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_V2_CCFormat));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_CC_GET_WRITE_ADDR:
                case E_VDEC_EX_V2_USER_CMD_CC_GET_READ_ADDR:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_CC_GET_RW_ADDR, spt_VDEC_EX_GET_CC_GET_RW_ADDR,buffer_arg,sizeof(buffer_arg));
                    kernel_IO_Param->param[0] = (void*)(&eCCFormat);//kmalloc(sizeof(VDEC_EX_CCFormat),GFP_KERNEL);
                    kernel_IO_Param->param[1] = (void*)(&u32Param0);//kmalloc(sizeof(MS_U32),GFP_KERNEL);
                    copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                    copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_CCFormat));
                    u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                    copy_to_user((void*)kernel_user_IO_Param->param[1],(void*)kernel_IO_Param->param[1],sizeof(MS_U32));
                    copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_MAIN_STREAM_ID:
                case E_VDEC_EX_V2_USER_CMD_GET_SUB_STREAM_ID:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_STREAM_ID, spt_VDEC_EX_GET_STREAM_ID,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_StreamId stStremId;
                        kernel_IO_Param->param[0] = (void*)(&stStremId);//kmalloc(sizeof(VDEC_EX_V2_Frame_packing_SEI),GFP_KERNEL);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_StreamId));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_FPA_SEI:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FPA_SEI, spt_VDEC_EX_GET_FPA_SEI,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_Frame_packing_SEI stFramePack;
                        kernel_IO_Param->param[0] = (void*)(&stFramePack);//kmalloc(sizeof(VDEC_EX_V2_Frame_packing_SEI),GFP_KERNEL);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_Frame_packing_SEI));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_FPA_SEI_EX:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FPA_SEI_EX, spt_VDEC_EX_GET_FPA_SEI_EX,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_Frame_packing_SEI_EX stFramePackEX;
                        kernel_IO_Param->param[0] = (void*)(&stFramePackEX);//kmalloc(sizeof(VDEC_EX_V2_Frame_packing_SEI_EX),GFP_KERNEL);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_V2_Frame_packing_SEI_EX));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_Frame_packing_SEI_EX));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_DCV_SEI:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FPA_SEI_EX, spt_VDEC_EX_GET_FPA_SEI_EX,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_DisplayColourVolume_SEI stDCVSEIInfo;
                        kernel_IO_Param->param[0] = (void*)(&stDCVSEIInfo);//kmalloc(sizeof(VDEC_EX_V2_Frame_packing_SEI_EX),GFP_KERNEL);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_V2_DisplayColourVolume_SEI));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_DisplayColourVolume_SEI));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_VUI_DISP_INFO:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FPA_SEI_EX, spt_VDEC_EX_GET_FPA_SEI_EX,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_AVC_VUI_DISP_INFO stVUI_DISP_Info;
                        kernel_IO_Param->param[0] = (void*)(&stVUI_DISP_Info);//kmalloc(sizeof(VDEC_EX_V2_Frame_packing_SEI_EX),GFP_KERNEL);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_V2_AVC_VUI_DISP_INFO));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_AVC_VUI_DISP_INFO));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;

                case E_VDEC_EX_V2_USER_CMD_GET_NEXT_DISP_FRAME_INFO_EXT:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FPA_SEI_EX, spt_VDEC_EX_GET_FPA_SEI_EX,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_FrameInfoExt stFrameInfoExt;
                        kernel_IO_Param->param[0] = (void*)(&stFrameInfoExt);//kmalloc(sizeof(VDEC_EX_V2_Frame_packing_SEI_EX),GFP_KERNEL);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_FrameInfoExt));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_FrameInfoExt));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_CRC_VALUE:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_CRC_VALUE, spt_VDEC_EX_GET_CRC_VALUE,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_CrcValue stCrc;
                        kernel_IO_Param->param[0] = (void*)(&stCrc);//kmalloc(sizeof(VDEC_EX_V2_Frame_packing_SEI_EX),GFP_KERNEL);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        //copy_from_user((void*)kernel_IO_Param->param[0],(void*)user_IO_Param->param[0],sizeof(VDEC_EX_V2_CrcValue));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_CrcValue));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_FRAME_INFO_EX:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_GET_FRAME_INFO_EX, spt_VDEC_EX_GET_FRAME_INFO_EX,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_FrameInfoEX stFrameInfo;
                        kernel_IO_Param->param[0] = (void*)(&stFrameInfo);//kmalloc(sizeof(VDEC_EX_V2_FrameInfoEX),GFP_KERNEL);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_FrameInfoEX));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_GET_GST_TIMING:
                    if(1)
                    {
                        VDEC_EX_MVOPInfo stMVOPInfo;
                        kernel_IO_Param->param[0] = (void*)(&stMVOPInfo);//kmalloc(sizeof(VDEC_EX_V2_FrameInfoEX),GFP_KERNEL);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_MVOPInfo));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                default:
                    break;
            }
            break;
        case E_VDEC_EX_V2_CMD_PRE_SET_CONTROL:
            CPY_FROM_USER((void*)kernel_user_IO_Param, (VDEC_EX_V2_IO_Param*)pArgs, sizeof(VDEC_EX_V2_IO_Param));
            kernel_IO_Param->eUserCmd = kernel_user_IO_Param->eUserCmd;
            switch(kernel_IO_Param->eUserCmd)
            {
                case E_VDEC_EX_V2_USER_CMD_PREGETSTATUS:
                    //u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_PREGETSTATUS, spt_VDEC_EX_PREGETSTATUS,buffer_arg,sizeof(buffer_arg));
                    if(1)
                    {
                        VDEC_EX_V2_Status stStatus;
                        kernel_IO_Param->param[0] = (void*)(&stStatus);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->param[0],(void*)kernel_IO_Param->param[0],sizeof(VDEC_EX_V2_Status));
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_MFCODEC_MODE:
                    if(1)
                    {
                        VDEC_EX_MFCodec_mode eMFCCodec;
                        kernel_IO_Param->param[0] = (void*)(&eMFCCodec);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_MFCodec_mode));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_PRESET_ENABLETURBOMODE:
                case E_VDEC_EX_V2_USER_CMD_PRESETSINGLEDECODE:
                case E_VDEC_EX_V2_USER_CMD_VPU_SECURITY_MODE:
                case E_VDEC_EX_V2_USER_CMD_HVD_COL_BBU_MODE:
                case E_VDEC_EX_V2_USER_CMD_HVD_ONE_PENDING_BUFFER_MODE:
                case E_VDEC_EX_V2_USER_CMD_MVD_HWBUFFER_REMAPPING_MODE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_BOOL, spt_VDEC_EX_IO_BOOL,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_PRESET_DECODE_MODE:
                    if(1)
                    {
                        VDEC_EX_DecModCfg stDecModCfg;
                        kernel_IO_Param->param[0] = (void*)(&stDecModCfg);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_DecModCfg));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_FORCE_START_NON_I_SLICE:
                case E_VDEC_EX_V2_USER_CMD_THUMBNAIL_MODE:
                case E_VDEC_EX_V2_USER_CMD_ENABLE_SEAMLESS_MODE:
                case E_VDEC_EX_V2_USER_CMD_SET_SHAREMEMORY_BASE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_U32, spt_VDEC_EX_IO_U32,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SYSTEM_PRESET_VPU_CLOCK:
                case E_VDEC_EX_V2_USER_CMD_SYSTEM_PRESET_HVD_CLOCK:
                case E_VDEC_EX_V2_USER_CMD_SYSTEM_PRESET_MVD_CLOCK:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SYSTEM_PRESET_CLOCK, spt_VDEC_EX_SYSTEM_PRESET_CLOCK,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_SETPOWERSTATE:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_SET_POWERSTATE, spt_VDEC_EX_SET_POWERSTATE,buffer_arg,sizeof(buffer_arg));
                    break;
                case E_VDEC_EX_V2_USER_CMD_HVD_IAPGN_BUF_SHARE_BW_MODE:
                    if(1)
                    {
                        VDEC_EX_IapGnBufShareBWMode stBufShareBW;
                        kernel_IO_Param->param[0] = (void*)(&stBufShareBW);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_IapGnBufShareBWMode));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                case E_VDEC_EX_V2_USER_CMD_CONNECT_DISPLAY_PATH:
                    if(1)
                    {
                        VDEC_EX_DynmcDispPath stDynmcDispPath;
                        kernel_IO_Param->param[0] = (void*)(&stDynmcDispPath);
                        copy_from_user((void*)kernel_IO_Param->StreamID,(void*)kernel_user_IO_Param->StreamID,sizeof(VDEC_EX_V2_StreamId));
                        copy_from_user((void*)kernel_IO_Param->param[0],(void*)kernel_user_IO_Param->param[0],sizeof(VDEC_EX_DynmcDispPath));
                        u32Ret = UtopiaIoctl(pInstanceTmp,u32Cmd,kernel_IO_Param);
                        copy_to_user((void*)kernel_user_IO_Param->pRet,(void*)kernel_IO_Param->pRet,sizeof(VDEC_EX_V2_Result));
                    }
                    break;
                default:
                    break;
            }
            break;
        case E_VDEC_EX_V2_CMD_POST_SET_CONTROL:
            CPY_FROM_USER((void*)kernel_user_IO_Param, (VDEC_EX_V2_IO_Param*)pArgs, sizeof(VDEC_EX_V2_IO_Param));
            kernel_IO_Param->eUserCmd = kernel_user_IO_Param->eUserCmd;

            switch(kernel_IO_Param->eUserCmd)
            {
                case E_VDEC_EX_V2_USER_CMD_SYSTEM_POSTSET_CLEAR_PROCESS_RELATED:
                    u32Ret=UADPBypassIoctl(pInstanceTmp,u32Cmd,pArgs,spt_VDEC_EX_IO_U32, spt_VDEC_EX_IO_U32,buffer_arg,sizeof(buffer_arg));
                    break;
                default:
                    break;
            }
            break;
        default:
            break;
    }
    return u32Ret;
}




