obj-$(CONFIG_WEBOS)		+= webos.o
obj-$(CONFIG_LOW_MEM_NOTIFY)	+= low-mem-notify.o
obj-$(CONFIG_SYSRQ_LOG_PRINT)	+= sysrq.o
obj-$(CONFIG_KMSG_RAW)		+= kmsg_raw.o
obj-$(CONFIG_USER_INITCALL)	+= user_initcall.o
obj-$(CONFIG_FAULT_NOTIFIER)	+= fault_notifier.o

obj-y				+= logger/
